version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_local
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_local
    volumes: 
      - ./backend/src:/var/www/html
    ports: 
      - "8000:8000"
    depends_on:
      - db

