version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_local
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "8000:8000"

